spring:
  application:
    name: service0
eureka:
  client:
    serviceUrl:
      defaultZone: http://TF017319:8080/eureka/  #注册中心地址
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 8081
